### ISSUE TITLE
Allow unknown properties by default

### ISSUE THREAD

**Issue by Marcono1234** [Marcono1234/gson-record-type-adapter-factory#1]
### Proposed change
Currently `RecordTypeAdapterFactory.DEFAULT` disallows unknown properties in the JSON data. The logic should be reversed, unknown properties should be allowed by default and only disallowed when explicitly configured.

📢 Any feedback, arguing for the current behavior or for the new proposed behavior, is highly appreciated!

### Rationale
1. Especially when working with external services, often the JSON data includes information which is not relevant for an application. It is therefore common to omit irrelevant properties from the model classes.
2. Over time services producing JSON data might be extended to include additional properties. If applications using these services by default disallow unknown properties, such changes to the JSON data will break the applications, even if the change itself would still be backward compatible.

This change request does not cover the behavior of other configuration methods, such as `allowMissingComponentValues()`. Their behavior might not be a suitable default for all use cases and users should therefore explicitly make the choice to enable them.

### Considerations
The documentation for the newly added method `RecordTypeAdapterFactory.Builder.disallowUnknownProperties()` should include a warning that disallowing unknown properties can break backward compatibility when a service (e.g. JSON REST API) is extended with new properties, see rationale 2 listed above.

The API changes will be backward incompatible, but that is probably acceptable given that this library is currently still described as experimental.

**Comment by SIMULATAN** [comment]
👍 if I remember correctly, GSON has this option on per default so it will probably be less confusing for the users to have both libraries behave the same way in that regard.

Also, I believe that in the majority of the use cases, this behaviour would be better because APIs can change randomly without knowing it and thus break your application.

**Comment by Marcono1234** [comment]
Thanks a lot for your feedback! I have changed the default behavior to allow unknown properties.
